### ISSUE TITLE
v-repeat current object not in element.$scope

### ISSUE THREAD

**Issue by twltwl** [teropa/angular-virtual-dom#11] opened 2015-02-09 11:57 UTC
If I have a v-repeat with a custom directive attached then I cant access the row from within my directive.
rows = [{...},{...}]
v-repeat='currentRow in rows' myDirective
...
//myDirective
linkVirtual: function(element){
  console.log(element.$scope.currentRow); //undefined
}

**Comment by teropa** [comment] 2015-02-09 12:08
This is working for me - if possible, could you edit it to reproduce your situation? http://plnkr.co/edit/w63xVCitVSBdWACp2Pdc?p=preview

One possible cause is that since we don't yet implement priority (#7), it matters in which order directives are specified on the element.

**Comment by twltwl** [comment] 2015-02-09 12:31
I tried your example and the console.logs says undefined when using FF. 
It seems to work when using Chrome though

**Comment by teropa** [comment] 2015-02-09 12:50
Ah-ha, so it seems. Firefox iterates attributes from right to left. In any case, we should rely on any order and instead support priority. Will fix ASAP.

**Comment by teropa** [comment] 2015-02-09 15:50
Fixed in 0.1.0

**Closed as completed by teropa** 2015-02-09 15:50 UTC
